name: Build and Deploy to EC2

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: nabin011011/git-petclinic:v1.0

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Install Docker only if not installed
            if ! command -v docker &> /dev/null; then
              echo "Docker not found. Installing..."
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
            else
              echo "Docker already installed."
            fi

            # Pull the latest Docker image
            sudo docker pull nabin011011/git-petclinic:v1.0

            # Stop and remove existing container if it exists
            if [ "$(sudo docker ps -aq -f name=petclinic)" ]; then
              echo "Stopping and removing existing petclinic container..."
              sudo docker stop petclinic
              sudo docker rm petclinic
            fi

            # Run the container
            sudo docker run -d -p 8080:8080 --name petclinic nabin011011/git-petclinic:v1.0
